import type { AnalysisResult, ScenarioInput } from "./schemas";
import { asList } from "./utils";

type Profile = { domain:string; actors:string[]; objects:string[]; goal:string; trigger:string; source:string; target:string; outcome:string; riskyDecision:string; aiUse:string };
const profiles: Array<[RegExp,Profile]> = [
  [/投诉|客服|客户服务|工单|售后|呼叫中心/,{domain:"客户服务 / 客诉运营",actors:["客服专员","业务责任部门","客服主管"],objects:["客户诉求","服务工单","处置记录"],goal:"缩短响应时长并提高一次解决率",trigger:"客户通过服务渠道提交诉求",source:"客服渠道与工单系统",target:"客户服务工单系统",outcome:"分类准确、责任明确且可追踪的处置工单",riskyDecision:"赔付、公开承诺与重大客诉结论",aiUse:"理解诉求、提取事实、分类摘要与回复草稿"}],
  [/入职|招聘|员工|人事|HR|离职/,{domain:"人力资源 / 员工服务",actors:["HR 专员","用人部门","新员工","信息安全管理员"],objects:["员工档案","入职任务","账号与权限申请"],goal:"缩短办理周期并减少资料遗漏",trigger:"候选人接受录用或员工状态变化",source:"招聘系统、员工提交材料与 HR 系统",target:"HR 系统与员工服务工作台",outcome:"完整员工档案和可追踪的跨部门任务",riskyDecision:"录用、薪酬、解雇及高权限账号审批",aiUse:"材料识别、信息提取、政策问答与通知草稿"}],
  [/合同|法务|条款|协议/,{domain:"法务 / 合同管理",actors:["业务经办人","法务专员","合同审批人"],objects:["合同文本","条款风险","审批记录"],goal:"提升审查效率并保持法律风险可控",trigger:"业务提交合同审查申请",source:"合同管理系统、邮件或受控文件目录",target:"合同管理与审批系统",outcome:"带证据定位的风险清单和审批任务",riskyDecision:"合同放行、法律结论与对外承诺",aiUse:"条款抽取、版本比对、风险提示和修改建议草稿"}],
  [/线索|销售|商机|营销|客户跟进/,{domain:"销售运营 / 线索管理",actors:["销售代表","销售运营","销售主管"],objects:["销售线索","客户互动记录","商机"],goal:"提高有效线索转化率并减少跟进遗漏",trigger:"新线索进入或到达跟进节点",source:"营销渠道、CRM 与沟通记录",target:"CRM 线索与商机模块",outcome:"分级线索、下一步任务和完整跟进记录",riskyDecision:"报价、折扣、合同承诺与客户敏感沟通",aiUse:"线索摘要、意向识别、个性化沟通草稿"}],
  [/采购|供应商|询价|招标/,{domain:"采购 / 供应链管理",actors:["采购专员","需求部门","采购审批人"],objects:["采购需求","供应商报价","采购订单"],goal:"缩短采购周期并提升比价与审批透明度",trigger:"需求部门提交采购申请",source:"采购平台、供应商文件与 ERP",target:"采购管理系统或 ERP",outcome:"可审计的比价结果、审批记录与采购任务",riskyDecision:"供应商选定、定标、高金额采购与付款",aiUse:"报价文件提取、差异归纳和供应商材料摘要"}],
  [/生产|制造|质检|设备|工厂|排产/,{domain:"制造运营 / 生产管理",actors:["生产计划员","现场操作员","质量工程师"],objects:["生产工单","设备状态","质量异常"],goal:"降低等待与异常处置时间并提高过程可追溯性",trigger:"生产计划下达或设备/质量事件发生",source:"MES、设备系统与现场记录",target:"MES 与异常管理系统",outcome:"受控生产任务、异常闭环与追溯记录",riskyDecision:"停线、质量放行、设备控制与工艺参数修改",aiUse:"异常记录归类、知识检索和处置建议草稿"}],
  [/患者|医疗|门诊|医院|病历/,{domain:"医疗服务 / 运营支持",actors:["医务人员","运营人员","审核人员"],objects:["服务申请","业务记录","随访任务"],goal:"减少信息重复录入并提升服务衔接效率",trigger:"患者服务事件或业务任务到达",source:"授权业务系统与人工提交材料",target:"医疗业务工作台",outcome:"完整、可审核的业务记录与后续任务",riskyDecision:"诊断、处方、治疗建议与患者安全相关结论",aiUse:"文档信息提取、记录摘要和非诊疗类服务分流"}],
];
const fallback:Profile={domain:"企业运营 / 业务流程管理",actors:["业务经办人","业务负责人","审批人"],objects:["业务申请","处理任务","结果记录"],goal:"缩短处理周期、减少重复劳动并提升可追溯性",trigger:"业务事件发生或用户提交申请",source:"业务系统、文件或人工提交渠道",target:"目标业务系统或任务平台",outcome:"可追踪的业务结果、异常任务与审计记录",riskyDecision:"高风险写入、删除、审批与对外承诺",aiUse:"非结构化信息提取、分类、摘要和内容草稿"};

function profileFor(input:ScenarioInput){const text=`${input.scenarioName} ${input.scenarioDescription}`;return profiles.find(([r])=>r.test(text))?.[1]??fallback}
export function isFinancialReconciliation(input:ScenarioInput){return /对账|银行流水|总账|账簿/.test(`${input.scenarioName} ${input.scenarioDescription}`)}
const list=(value:string|undefined,fallbackValue:string[])=>value?.trim()?asList(value):fallbackValue;

export function createIndustryMockAnalysis(input:ScenarioInput):AnalysisResult{
  const p=profileFor(input); const scope=input.analysisScope??"domain"; const actors=list(input.actors,p.actors); const objects=list(input.businessObjects,p.objects); const goals=list(input.businessGoal,[p.goal]); const triggers=list(input.triggers,[p.trigger]); const hasSystems=Boolean(input.systemsAndRelations?.trim()); const dynamic=/跨系统|多系统|异常|反复|动态/.test(`${input.currentProcess??""} ${input.painPoints??""}`); const agentNeeded=dynamic&&hasSystems;
  const source=input.inputDataAndSources?.trim()||p.source; const target=input.targetResultsAndDestinations?.trim()||p.target;
  return {
    analysisMeta:{analysisMode:input.analysisMode,analysisScope:scope,generatedAt:new Date().toISOString(),confidence:input.analysisMode==="deep"?.84:input.analysisMode==="standard"?.75:.66,overallConclusion:`${input.scenarioName}适合先盘点候选场景并按价值、可行性和风险排序，再以“规则 + 工作流 + API”为确定性主链路深化优先场景。AI 可辅助${p.aiUse}。${agentNeeded?"对跨系统异常调查可小范围试点受控 Agent":"当前信息不足以证明需要 Agent，固定流程不应强行 Agent 化"}；${p.riskyDecision}必须保留人工控制。`},
    opportunityPortfolio:[
      {scenarioId:"S1",scenarioName:`${input.scenarioName}统一受理与分流`,businessArea:p.domain,problem:"入口分散、字段不一致，人工分类与转派成本高",targetValue:"统一入口、减少重复录入并缩短首次处理时间",candidateTechnologies:["API","规则引擎","工作流",...(p.aiUse?["AI"]:[])],businessValue:5,feasibility:4,risk:2,priority:"P0",recommendation:"优先建立字段标准、分类规则和任务状态机"},
      {scenarioId:"S2",scenarioName:`${input.scenarioName}智能内容理解`,businessArea:p.domain,problem:"非结构化材料依赖人工阅读和归纳",targetValue:p.aiUse,candidateTechnologies:["AI","规则","人工复核"],businessValue:4,feasibility:4,risk:3,priority:"P0",recommendation:"用历史样本建立评估集，低置信度转人工"},
      {scenarioId:"S3",scenarioName:`${input.scenarioName}跨系统协同闭环`,businessArea:p.domain,problem:"状态分散、等待和催办难以追踪",targetValue:`把结果闭环到${target}`,candidateTechnologies:["工作流","API","消息通知"],businessValue:4,feasibility:3,risk:3,priority:"P1",recommendation:"先确认接口、幂等键、审批矩阵与失败接管"},
      {scenarioId:"S4",scenarioName:`${input.scenarioName}异常调查助手`,businessArea:p.domain,problem:"复杂异常需要反复查询多方证据",targetValue:"缩短异常调查时间并沉淀证据链",candidateTechnologies:["AI",...(agentNeeded?["Agent"]:[]),"只读 API","人工"],businessValue:3,feasibility:2,risk:4,priority:"P2",recommendation:"只读小流量试点；未证明动态多工具需求前不使用 Agent"}
    ],
    scenarioUnderstanding:{scenarioName:input.scenarioName,businessDomain:p.domain,businessGoals:goals,actors,businessObjects:objects,triggers,boundaries:["本方案只做分析设计，不直接执行真实业务操作",`${p.riskyDecision}不自动执行`,"未确认的系统接口、字段与权限均按待确认处理"],expectedResults:[p.outcome,"异常处理任务","过程与审批审计记录"]},
    informationCompleteness:{knownFacts:[`用户描述：${input.scenarioDescription}`,...(input.currentProcess?[`当前流程：${input.currentProcess}`]:[]),...(input.painPoints?[`当前痛点：${input.painPoints}`]:[])],assumptions:["业务对象存在唯一业务编号或可组合生成幂等键","目标系统可提供受控接口；若无接口再评估稳定页面 RPA","异常和高风险结果可进入人工任务队列"],openQuestions:["来源与目标系统的具体模块、接口和权限是什么？","关键字段、数据质量标准和业务时效 SLA 是什么？",`谁有权最终决定${p.riskyDecision}？`]},
    businessLayers:{
      l1Goals:goals.map(goal=>({goal,metric:"处理周期、自动化覆盖率、一次通过率和异常率（基线待确认）",boundary:`不自动执行${p.riskyDecision}`})),
      l2Scenario:{role:actors.join("、"),trigger:triggers.join("、"),object:objects.join("、"),target:p.outcome,scope:input.constraints||"授权组织、渠道、业务类型与时间范围（待确认）"},
      l3Process:[{stepNo:1,name:"受理与数据获取",input:source,output:"校验后的业务上下文",branch:"资料齐全进入处理，缺失则补充",exception:"来源不可用或格式异常",manualControl:"连续失败或敏感数据异常转人工"},{stepNo:2,name:"规则校验与内容分析",input:"业务上下文与规则",output:"分类、校验结果与处理建议",branch:"确定性规则自动通过；复杂内容进入 AI 辅助",exception:"证据冲突、低置信度或规则未覆盖",manualControl:"高风险和低置信度结果复核"},{stepNo:3,name:"审批、写回与通知",input:"处理结果与证据",output:p.outcome,branch:"普通结果按工作流写回",exception:"写回失败、重复请求或审批拒绝",manualControl:`${p.riskyDecision}由授权人员确认`}],
      l4Tasks:[{taskId:"T1",taskName:"获取并校验业务数据",purpose:"形成可信输入",input:source,output:"标准化业务数据",owner:actors[0]||"业务经办人"},{taskId:"T2",taskName:"规则判断与内容理解",purpose:"识别确定性结果及复杂信息",input:"标准化数据与业务规则",output:"分类、校验和建议",owner:"业务处理服务"},{taskId:"T3",taskName:"异常复核与审批",purpose:"控制不确定性和业务风险",input:"异常、证据和处理建议",output:"人工结论与审批记录",owner:actors.at(-1)||"审批人"},{taskId:"T4",taskName:"结果写回与下游触发",purpose:"完成业务闭环",input:"已确认结果",output:p.outcome,owner:"工作流平台"}],
      l5AtomicActions:[{actionId:"A1",taskId:"T1",actionName:"按触发条件读取业务对象",operationType:"API；无接口且页面稳定时才用 RPA",targetObject:objects[0]},{actionId:"A2",taskId:"T1",actionName:"校验必填字段、格式和重复记录",operationType:"规则/Python",targetObject:"标准化数据集"},{actionId:"A3",taskId:"T2",actionName:p.aiUse,operationType:"AI",targetObject:"非结构化内容"},{actionId:"A4",taskId:"T3",actionName:"复核证据并记录决定",operationType:"人工审批",targetObject:"异常处理任务"},{actionId:"A5",taskId:"T4",actionName:"以业务键幂等写回结果",operationType:"API/工作流",targetObject:"目标业务记录"}]},
    dataClosedLoop:{dataSources:[{dataObject:objects[0]||"业务对象",sourceSystem:source,sourceLocation:"具体系统、模块、页面或接口待确认",provider:actors[0]||"业务经办人",trigger:triggers.join("、"),acquisitionMethod:"优先使用受支持 API；文件上传或页面操作采用受控适配",format:"JSON、表格、文档或表单（待确认）",keyFields:["业务唯一标识","状态","创建/更新时间","责任人"],qualityRequirements:["必填字段完整","业务标识唯一","来源与时间可追溯"]},{dataObject:"规则与参考资料",sourceSystem:"制度库/配置中心（待确认）",sourceLocation:"已发布规则版本",provider:"业务负责人",trigger:"分析任务启动",acquisitionMethod:"只读检索",format:"结构化规则与受控文档",keyFields:["规则编号","版本","生效日期"],qualityRequirements:["仅使用有效版本","变更留痕"]}],dataFlows:[{stepNo:1,dataObject:"原始业务输入",inputSource:source,processAction:"获取、去重、格式与权限校验",intermediateResult:"标准化业务上下文",storage:"任务级加密临时区；按策略清理",outputResult:"可处理数据集",nextDestination:"规则与内容分析"},{stepNo:2,dataObject:"分析结果",inputSource:"业务上下文 + 规则资料",processAction:`确定性规则判断；AI 辅助${p.aiUse}`,intermediateResult:"带证据的分类、建议与置信度",storage:"任务状态与结果摘要",outputResult:"自动通过项和人工复核项",nextDestination:"审批/异常队列"},{stepNo:3,dataObject:"确认后的业务结果",inputSource:"规则结果或人工审批",processAction:"幂等写回、状态更新、通知",intermediateResult:"写回回执与审计事件",storage:"审计日志",outputResult:p.outcome,nextDestination:target}],resultDestinations:[{resultObject:p.outcome,targetSystem:target,targetLocation:"目标模块、对象和字段待确认",writebackMethod:"优先 API；使用业务键与请求号保证幂等",stateChange:"待处理→处理中→已完成/待人工/失败",downstreamConsumer:"业务经办人、负责人及后续流程",retentionAndAudit:"保留输入摘要、规则/模型版本、审批链和写回回执",failureHandling:"有限重试；禁止重复写入；失败保持原状态并创建人工任务"},{resultObject:"异常任务与分析报告",targetSystem:"任务平台/业务工作台（待确认）",targetLocation:"异常队列与受控报告目录",writebackMethod:"工作流创建任务并通知责任人",stateChange:"发现异常→待复核→已处理/已驳回",downstreamConsumer:actors.join("、"),retentionAndAudit:"按企业档案策略保留，访问留痕",failureHandling:"通知失败重试并升级责任人"}]},
    currentProblems:[{processStep:"业务受理",problemType:"信息不完整/重复录入",problem:input.painPoints||"输入渠道和字段标准尚未明确，易产生补充与返工",businessImpact:"处理周期延长，数据质量不稳定",severity:"高"},{processStep:"判断与流转",problemType:"规则分散/等待",problem:"规则、系统与责任边界缺少统一编排",businessImpact:"结果不一致，异常依赖人工追踪",severity:"高"},{processStep:"结果登记",problemType:"系统割裂/审计风险",problem:"结果落点、幂等键和下游状态变化待明确",businessImpact:"可能重复写入或形成流程断点",severity:"中"}],
    taskTechnologyMappings:[{taskId:"T1",taskName:"获取并校验业务数据",taskType:"数据采集与校验",currentMode:"人工或现状待确认",recommendedMode:["API","规则","工作流"],aiRole:"不用于确定性字段校验",rpaRole:"仅在无 API 且界面稳定时采集",apiRole:"优先读取来源数据",pythonSqlRole:"清洗、去重、格式转换",workflowRole:"调度、重试和状态管理",agentRole:"不需要",humanReview:"来源异常或敏感权限问题",rationale:"稳定接口和确定性规则最可靠",prerequisites:["确认系统接口","字段字典","权限与幂等键"],riskLevel:"中",priority:"P0"},{taskId:"T2",taskName:"规则判断与内容理解",taskType:"规则 + 非结构化理解",currentMode:"人工判断",recommendedMode:["规则引擎","AI","Python/SQL"],aiRole:p.aiUse,rpaRole:"不适用",apiRole:"读取业务上下文和参考资料",pythonSqlRole:"精确计算与批量处理",workflowRole:"按置信度和风险分流",agentRole:"固定路径不需要 Agent",humanReview:"低置信度、冲突和高风险结果",rationale:"精确判断与概率性理解应分离",prerequisites:["规则可配置","评估样本","置信度阈值"],riskLevel:"中",priority:"P0"},{taskId:"T3",taskName:"异常复核与审批",taskType:"风险决策",currentMode:"人工",recommendedMode:["工作流","人工审批",...(agentNeeded?["Agent（条件式）"]:[])],aiRole:"只提供证据摘要和建议",rpaRole:"不用于审批",apiRole:"查询授权证据",pythonSqlRole:"复算关键指标",workflowRole:"审批、升级和超时管理",agentRole:agentNeeded?"只读调查多系统异常":"当前不需要",humanReview:`${p.riskyDecision}必须人工决定`,rationale:"高风险决定不可交给模型",prerequisites:["审批矩阵","工具白名单","审计要求"],riskLevel:"高",priority:"P0"},{taskId:"T4",taskName:"结果写回与通知",taskType:"确定性状态变更",currentMode:"人工登记",recommendedMode:["API","工作流","规则"],aiRole:"可生成通知草稿，不控制写入",rpaRole:"无接口时才评估",apiRole:"幂等写回和读取回执",pythonSqlRole:"批量结果整理",workflowRole:"状态机、重试和通知",agentRole:"不需要",humanReview:"高风险写入前审批",rationale:"可枚举链路应由工作流控制",prerequisites:["写接口","幂等与重试协议","回滚方案"],riskLevel:"高",priority:"P1"}],
    targetProcess:[{stepNo:1,name:"统一受理与质量校验",executor:"业务工作流",technology:["API","规则","Python/SQL"],input:source,output:"标准化业务上下文",normalPath:"校验通过进入处理",exceptionPath:"缺失信息进入补充任务",humanGate:"敏感权限或来源异常"},{stepNo:2,name:"规则处理与 AI 辅助理解",executor:"规则服务/AI 辅助服务",technology:["规则引擎","AI","工作流"],input:"标准化数据与有效规则",output:"带证据和置信度的建议",normalPath:"确定性且低风险结果继续",exceptionPath:"冲突、低置信度进入人工队列",humanGate:`涉及${p.riskyDecision}时强制人工`},{stepNo:3,name:"审批、幂等写回与通知",executor:"审批人/工作流平台",technology:["人工审批","API","工作流"],input:"处理结果与审批记录",output:p.outcome,normalPath:"写回成功后更新状态并通知下游",exceptionPath:"重试失败保持原状态并转人工",humanGate:"高风险写入前最终确认"}],
    technologySummary:{aiSuitable:[p.aiUse],rpaSuitable:["仅限无可用 API 且页面稳定的重复录入/下载"],apiSuitable:["来源数据读取","结果幂等写回","任务与状态同步"],rulesSuitable:["必填校验","阈值和状态路由","审批矩阵"],pythonSqlSuitable:["数据清洗、去重、转换与精确计算"],workflowSuitable:["受理—处理—复核—写回—通知主链路"],manualRequired:[p.riskyDecision,"证据冲突、低置信度与越界异常"]},
    agentDesign:{necessary:agentNeeded,maturityLevel:agentNeeded?"M2":"M1",rationale:agentNeeded?"输入显示存在跨系统和异常调查，可在固定主流程之外试点只读 Agent；最终决定和写回仍由工作流与人工控制。":"当前场景可由固定工作流、规则、API 与 AI 单点能力覆盖，没有足够动态特征证明 Agent 必要。",responsibilities:["汇总业务上下文与证据",...(agentNeeded?["根据证据缺口选择白名单只读查询"]:[]),"生成可追溯的处理建议"],callableTools:["业务对象只读查询","规则检索","状态查询"],fixedWorkflowParts:["输入校验","风险分流","审批","幂等写回","通知"],boundaries:[`不得自行决定${p.riskyDecision}`,"不得绕过权限与审批","不得删除或覆盖原始数据"],exitConditions:["低置信度或证据冲突","工具连续失败","超出授权范围","命中高风险规则","人工要求接管"]},
    governance:[{risk:"数据或权限越界",control:"最小权限、字段脱敏、只读优先和授权范围校验",owner:"系统与数据负责人",auditEvidence:"访问日志和权限变更记录"},{risk:"AI 建议错误或缺少证据",control:"置信度阈值、证据引用、评估集和人工复核",owner:"业务负责人",auditEvidence:"模型版本、建议摘要与复核记录"},{risk:"重复或错误写回",control:"业务键+请求号幂等、写前校验、失败保持原状态",owner:"目标系统负责人",auditEvidence:"请求摘要、响应码和写回回执"},{risk:"自动化异常无人接管",control:"超时、有限重试、异常队列和人工接管 SLA",owner:"流程运营负责人",auditEvidence:"重试、升级和接管记录"}],
    implementationRoadmap:[{phase:"阶段一：流程与数据基线",goal:"明确边界并跑通只读试点",scope:["单一业务类型","只读数据","离线评估"],deliverables:["流程图","字段字典","规则清单","指标基线"],dependencies:["业务样本","系统与数据负责人"],acceptanceCriteria:["来源和落点明确","规则可复算","高风险动作零自动执行"]},{phase:"阶段二：确定性闭环",goal:"上线受控工作流与幂等写回",scope:["规则处理","人工审批","状态写回","审计"],deliverables:["工作流","审批矩阵","接口适配","监控与接管机制"],dependencies:["测试接口","权限与审计方案"],acceptanceCriteria:["重复写入为 0","异常可追踪率 100%","人工可随时接管"]},{phase:"阶段三：智能能力评估",goal:"以业务指标验证 AI/Agent 的增量价值",scope:[p.aiUse,agentNeeded?"只读异常调查 Agent":"暂不引入 Agent"],deliverables:["评估集","灰度方案","效果与风险报告"],dependencies:["标注样本","工具白名单","退出阈值"],acceptanceCriteria:["准确率和采纳率达到业务门槛","高风险结果 100% 人工控制","无越权调用"]}],
    valueAssessment:{businessValue:4,standardization:input.currentProcess?4:3,dataMaturity:input.inputDataAndSources?4:2,technicalFeasibility:4,riskControllability:4,reusability:4,overallScore:input.analysisMode==="deep"?78:72,conclusion:`${input.scenarioName}具备改造价值。优先补齐来源、字段、接口、结果落点和审批矩阵，再从确定性工作流切入；是否引入 Agent 应由异常路径比例和多系统调查成本决定。`}
  };
}
